from collections import deque
queue = deque()
queue.append(5)
queue.append(4)
queue.append(3)
queue.append(7)
queue.popleft()
queue.append(1)
queue.append(4)
queue.popleft()
print(list(queue))
queue.reverse()
print(list(queue))